steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/petsapp:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/petsapp:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/petsapp:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/run"
    args:
      - "deploy"
      - "petsapp"
      - "--image"
      - "gcr.io/$PROJECT_ID/petsapp:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/petsapp:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/petsapp:latest"

timeout: "1800s"
