services:
  - type: web
    name: petsapp
    runtime: docker
    dockerfile: Dockerfile
    region: oregon
    
    healthCheckPath: /
    
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
    
    autoDeploy: true
